GET http://127.0.0.1:8000 HTTP/1.1
Content-Type: application/json

{
    "test": "info"
}

### robots.txt
GET http://127.0.0.1:8000/robots.txt HTTP/1.1

### jinja2
GET http://127.0.0.1:8000/jinja2.html HTTP/1.1